[package]
name = "koi-lang"
version = "0.1.2"
edition = "2021"
authors = ["Joseph Caruso <jcaru@jcaru.com>"]
description = "ğŸŸ High-level programming language ğŸŸ Cross-platform ğŸŸ Blazing performance ğŸŸ Static linking ğŸŸ"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "koi_api"
path = "src/mod.rs"

[[bin]]
name = "koi"
path = "src/main.rs"

[dependencies]
